
---

#- include_vars: ../../../group_vars/db_server

- name: Install Openldap clients
  yum: name={{ item }} state=installed
  with_items:
    - openldap-clients

- name: Install the Cloudera Manager Server Packages
  yum: name={{ item }} state=installed
  with_items:
    - cloudera-manager-daemons
    - cloudera-manager-server
    - cloudera-manager-agent

- name: Prepare Cloudera Manager Server External Database
  command: /usr/share/cmf/schema/scm_prepare_database.sh
             -f
             --host {{ hostvars[db_hostname]['inventory_hostname'] }}
             {{ databases.scm.type }} {{ databases.scm.name }} {{ databases.scm.user }} {{ databases.scm.pass }}
  changed_when: False

- name: Start the Cloudera Manager Server
  service: name={{ item }} state=restarted enabled=yes
  notify:
    - wait cloudera-scm-server
  with_items:
    - cloudera-scm-server
    - cloudera-scm-agent
