---
# cloudera os config

- name: Disable transparent huge page - defrag
  shell: echo "never" > /sys/kernel/mm/transparent_hugepage/defrag
 
- name: Disable transparent huge page - enabled
  shell: echo "never" > /sys/kernel/mm/transparent_hugepage/enabled
 
- name: VM swappiness - 1
  shell: echo "1" > /proc/sys/vm/swappiness
 
- name: Set VM swappiness - 2
  sysctl:
    name: vm.swappiness
    value: 1
    state: present
- name: install the latest version of ntp
  yum:
    name: ntp
    state: latest
 
- name: install the latest version of nscd
  yum:
    name: nscd
    state: latest
 
- name: install wget
  yum:
    name: wget
    state: latest
 
- name: Disable SELinux
  selinux:
    state: disabled
